// <auto-generated />
using System;
using CanineCorner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CanineCorner.Migrations
{
    [DbContext(typeof(CanineCornerContext))]
    [Migration("20190415202514_location")]
    partial class location
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CanineCorner.Models.DogInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Breed");

                    b.Property<DateTime>("DoB");

                    b.Property<string>("DogName");

                    b.Property<int>("Height");

                    b.Property<DateTime>("TodayDate");

                    b.Property<int>("User");

                    b.Property<int>("Weight");

                    b.HasKey("ID");

                    b.ToTable("DogInfo");
                });

            modelBuilder.Entity("CanineCorner.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocName");

                    b.Property<string>("LocType");

                    b.Property<int>("Rating");

                    b.Property<int>("ZipCode");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("CanineCorner.Models.Medical", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DogName");

                    b.Property<DateTime>("LastDateGiven");

                    b.Property<string>("MedName");

                    b.Property<string>("Periodicity");

                    b.Property<int>("User");

                    b.HasKey("ID");

                    b.ToTable("Medical");
                });
#pragma warning restore 612, 618
        }
    }
}
