// <auto-generated />
using System;
using CanineCorner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CanineCorner.Migrations
{
    [DbContext(typeof(CanineCornerContext))]
    [Migration("20190416172625_BreedStats")]
    partial class BreedStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CanineCorner.Models.Adaptibility", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Alone");

                    b.Property<int>("Apartment");

                    b.Property<int>("ColdWeather");

                    b.Property<int>("HotWeather");

                    b.Property<int>("NoviceOwners");

                    b.Property<int>("Overall");

                    b.Property<int>("Sensitivity");

                    b.HasKey("ID");

                    b.ToTable("Adaptibility");
                });

            modelBuilder.Entity("CanineCorner.Models.BreedInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Breed");

                    b.Property<int>("adaptability");

                    b.Property<int>("exercise");

                    b.Property<int>("friendliness");

                    b.Property<int>("grooming");

                    b.Property<int>("health");

                    b.Property<int>("training");

                    b.HasKey("ID");

                    b.ToTable("BreedInfo");
                });

            modelBuilder.Entity("CanineCorner.Models.DogInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Breed");

                    b.Property<DateTime>("DoB");

                    b.Property<string>("DogName");

                    b.Property<int>("Height");

                    b.Property<DateTime>("TodayDate");

                    b.Property<int>("User");

                    b.Property<int>("Weight");

                    b.HasKey("ID");

                    b.ToTable("DogInfo");
                });

            modelBuilder.Entity("CanineCorner.Models.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnergyLevel");

                    b.Property<int>("ExerciseNeed");

                    b.Property<int>("Intensity");

                    b.Property<int>("Overall");

                    b.Property<int>("Playfulness");

                    b.HasKey("ID");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("CanineCorner.Models.Friendliness", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OtherDogs");

                    b.Property<int>("Overall");

                    b.Property<int>("WithFamily");

                    b.Property<int>("WithKids");

                    b.Property<int>("WithStrangers");

                    b.HasKey("ID");

                    b.ToTable("Friendliness");
                });

            modelBuilder.Entity("CanineCorner.Models.Health", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("General");

                    b.Property<int>("Overall");

                    b.Property<int>("Size");

                    b.Property<int>("WeightGain");

                    b.HasKey("ID");

                    b.ToTable("Health");
                });

            modelBuilder.Entity("CanineCorner.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocName");

                    b.Property<string>("LocType");

                    b.Property<int>("Rating");

                    b.Property<int>("ZipCode");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("CanineCorner.Models.Medical", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DogName");

                    b.Property<DateTime>("LastDateGiven");

                    b.Property<string>("MedName");

                    b.Property<string>("Periodicity");

                    b.Property<int>("User");

                    b.HasKey("ID");

                    b.ToTable("Medical");
                });

            modelBuilder.Entity("CanineCorner.Models.Training", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Barking");

                    b.Property<int>("Easiness");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Mouthiness");

                    b.Property<int>("Overall");

                    b.Property<int>("PreyDrive");

                    b.Property<int>("Wanderlust");

                    b.HasKey("ID");

                    b.ToTable("Training");
                });
#pragma warning restore 612, 618
        }
    }
}
