SET IDENTITY_INSERT [dbo].[Location] ON
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (1, N'Fiesta Island Off-Leash Dog Park', N'Park', 92123, 4)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (2, N'Fiesta Island Off-Leash Dog Park', N'Park', 92117, 4)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (3, N'Woodglen Vista Dog Park', N'Park', 92071, 5)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (4, N'Kearney Mesa Dog Park', N'Park', 92111, 5)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (5, N'Nate''s Point Off-Leash Dog Park', N'Park', 92103, 4)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (6, N'Hotel Indigo San Diego Gaslamp Quarter', N'Hotel', 92101, 5)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (7, N'Ocean Beach Hotel', N'Hotel', 92107, 3)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (8, N'Hotel Solamar', N'Hotel', 92101, 4)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (9, N'The Bristol', N'Hotel', 92101, 5)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (10, N'Ocean Villa Inn', N'Hotel', 92107, 3)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (11, N'Best Western Mission Bay', N'Hotel', 92117, 1)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (12, N'Fred''s Mexican Cafe', N'Restaurant', 92110, 5)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (13, N'The Prado at Balboa Park', N'Restaurant', 92101, 4)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (14, N'The Landing Grille', N'Restaurant', 92109, 5)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (15, N'Station Tavern & Burgers', N'Restaurant', 92104, 5)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (16, N'The Patio on Lamont Street', N'Restaurant', 92109, 4)
INSERT INTO [dbo].[Location] ([ID], [LocName], [LocType], [ZipCode], [Rating]) VALUES (17, N'Pier Cafe', N'Restaurant', 92101, 4)
SET IDENTITY_INSERT [dbo].[Location] OFF
